### ISSUE TITLE
Autolevel unreliable, does not go past the first step

### ISSUE THREAD

**Issue by dgtlmoon** [chilipeppr/widget-autolevel#3]
I've seen this issue in other forums, and I can reproduce it reliably, auto-level probing completes the first check and then stops, does not go onto the next step.

I have had it working successfully once or twice but seems to be very intermittent.

I'm able to use the `Autolevel > Run > Run Test Probe` **100%** of the time and it always stops where I would expect it to.

Here's my actions

- Enable Autolevel widget
- Click Auto-fill, I can then see the grid on my board
![screenshot_2017-02-23_11-55-14](https://cloud.githubusercontent.com/assets/275001/23256245/f952f252-f9be-11e6-89ed-e558e6ff00ad.png)
- Click the [RUN] tab
- Click the Play button
![screenshot_2017-02-23_11-56-03](https://cloud.githubusercontent.com/assets/275001/23256281/11d2cc08-f9bf-11e6-9376-566de8b47fd0.png)
- Click "Let's get probing"
- Z-axis goes up 0.5mm
- Z-axis comes down, stops at 0.014 which is what I expect
- The end, nothing happens after this

I see some debug output

```
Going into mm and abs coord mode
Generating probe steps.
Generated 143 probe locations.
Starting probes
Moving to {x:-0.475,y:-0.475}
```

All settings seem fine, I am not breaking out of the max minimum-Z

![screenshot_2017-02-23_11-58-06](https://cloud.githubusercontent.com/assets/275001/23256367/66369a5e-f9bf-11e6-9695-8dac545c9d42.png)

I'm within version requirements

```$sys
[fb]  firmware build            440.20
[fv]  firmware version            0.97
[hp]  hardware platform           1.00
[hv]  hardware version            8.00
[id]  TinyG ID                    3X3566-KSL
```

**Comment by dgtlmoon** [comment]
It seems to be entering a paused state after each check, if i hit "pause" button twice, it will move onto the next step... where i have to hit the pause button twice..

![screenshot_2017-02-23_12-26-00](https://cloud.githubusercontent.com/assets/275001/23257239/44d03664-f9c3-11e6-9a64-6d3c269e0b84.png)

**Comment by dgtlmoon** [comment]
https://discuss.inventables.com/t/chilipeppr-auto-level-stopping/19811


> If anyone else runs up against this, it appears from the chilipeppr forums that this is a new bug introduced in the last few days. It's apparently been fixed in the TinyG version already, but hasn't been fixed over in the GRBL version yet... However there is a fork that someone built that does have the fix we can use. Seems to be a moving target, so please reference the chilipeppr G+ community for the latest forked version until they get it fixed officially...

Is this still the case? that's from feb 2016

**Comment by dgtlmoon** [comment]
if I press the 'send final gcode to workdesk' 
![screenshot_2017-02-23_17-17-34](https://cloud.githubusercontent.com/assets/275001/23267811/2510f22c-f9ec-11e6-922c-0a9bfb2193c0.png)
 button then re-run the autolevel by pressing the play button it works?

**Comment by chilipeppr** [comment]
Somebody else mentioned that if they didn't open the Eagle BRD widget it
worked ok. Do you see that? Also, what Javascript debug console errors do
you see if any? If you turn off the funnel icon in serial port console, do
you see any errors back from TinyG?

**Comment by dgtlmoon** [comment]
```G21 G90 (Use mm and abs coords)
{"Lbs":87}
{"r":{},"f":[1,0,32,133]}
G0 Z1.5
{"Lbs":77}
{"r":{},"f":[1,0,8,4401]}
{"sr":{"posz":1.998,"vel":24.09,"stat":5,"mpoz":1.998}}
{"qr":31}
G0 X-1 Y-1
{"Lbs":73}
{"r":{},"f":[1,0,11,70]}
{"sr":{"posz":1.974,"vel":202.51,"mpoz":1.974}}
{"qr":30}
G0 Z0.5
{"Lbs":63}
{"r":{},"f":[1,0,8,4401]}
{"sr":{"posz":1.907,"vel":476.09,"mpoz":1.859}}
{"qr":29}
{"qr":30}
{"qr":31}
{"sr":{"posx":-1.000,"posy":-1.000,"posz":0.508,"vel":180.98,"mpox":-1.000,"mpoy":-1.000,"mpoz":0.502}}
{"sr":{"posz":0.500,"vel":0.00,"stat":3,"mpoz":0.500}}
{"qr":32}
 G38.2 Z-10 F25
{"Lbs":74}
{"r":{},"f":[1,0,15,74]}
{"sr":{"stat":7,"coor":0}}
{"qr":32}
{"qr":31}
{"sr":{"posz":0.399,"vel":25.00,"momo":1,"mpoz":0.399}}
{"sr":{"posz":0.297,"mpoz":0.297}}
{"sr":{"posz":0.195,"mpoz":0.195}}
{"sr":{"posz":0.093,"mpoz":0.093}}
{"sr":{"posz":0.008,"vel":2.49,"mpoz":0.008}}
{"Lbs":42}
{"sr":{"vel":0.00,"stat":3,"coor":1,"momo":4}}
{"qr":32}
```


ah yes I see errors, no difference if the eagleboard widget is open/closed (off)

![screenshot_2017-02-24_11-25-51](https://cloud.githubusercontent.com/assets/275001/23300014/0756197c-fa84-11e6-9209-7047cbb8cf80.png)

**Comment by chilipeppr** [comment]
I'm hearing reports that the fix to the fadeOutUserObject that I published
yesterday fixed the problem. Try to reload ChiliPeppr in your browser and
see if you're good now. When seeing this email I was worried the publish
broke something further for you, but I've seen reports since then that the
fix worked.

**Comment by treib** [comment]
I'm getting the error that "fadeOutUserObject" is not found.  Looking at the latest commit, I see only a "fadeOutUserObjectOld" and a "fadeOutUserObjectJustinVersion".

Same end result: the probe stops when contact is made but doesn't continue on probing other locations.

Here's the console error in Chrome:

```
Uncaught TypeError: this.fadeOutUserObject is not a function
    at Object.showProbeMatrix (eval at globalEval (jquery-2.1.0.min.js:2), <anonymous>:285:26)
    at Object.toggleShowMatrix (eval at globalEval (jquery-2.1.0.min.js:2), <anonymous>:268:26)
    at Object.callback (eval at globalEval (jquery-2.1.0.min.js:2), <anonymous>:1339:30)
    at publish (amplify.js:35)
    at Object.publish (app.js:167)
    at Object.onWsMessage (eval at globalEval (jquery-2.1.0.min.js:2), <anonymous>:1533:40)
    at Object.eval (eval at globalEval (jquery-2.1.0.min.js:2), <anonymous>:232:22)
    at publish (amplify.js:35)
    at Object.publish (app.js:167)
    at Object.publishMsg (eval at globalEval (jquery-2.1.0.min.js:2), <anonymous>:1420:24)
```

**Comment by chilipeppr** [comment]
Uh oh. That would be my mistake. Just fixed it and republished from the
hotel in Barcelona. That's the danger of launching code without getting to
test it.

**Comment by dgtlmoon** [comment]
Thanks John! I'll retest tomorrow once I'm back in the office.

Kind of (un)related - the commit message `Made some changes to ChiliPeppr widget using Cloud9`, so cloud9 is committing somewhere else then you're pushing to github as a remote, or is it just a lazy commit message and it can support proper commit messages?

**Comment by chilipeppr** [comment]
All ChiliPeppr widgets and workspace Github repos have a runme.js script
that you can run to create the final HTML file that contains all
Javascript, CSS, and HTML for the widget or workspace. That runme.js script
also uploads to Github and does so with a default message. You can add a
custom git commit message, but if you're being lazy you just reload the
runme and you're done. So, yes, it's just being lazy.

**Comment by dgtlmoon** [comment]
ahuh cool! ok, some very interesting architecture there, i'll have to read more into it.

ok, so I'm still seeing an error in the console but it does appear to be working reliably... 

![screenshot_2017-02-26_22-11-50](https://cloud.githubusercontent.com/assets/275001/23343746/9bbb7740-fc70-11e6-8a16-7b5a5f925b9a.png)


serial port console output

```
{"Lbs":0}
{"r":{},"f":[1,0,16,75]}
{"sr":{"stat":7,"coor":0}}
{"qr":32}
{"qr":31}
{"sr":{"posz":0.170,"vel":32.00,"momo":1,"mpoz":0.170}}
{"sr":{"posz":0.040,"mpoz":0.040}}
{"sr":{"posz":-0.058,"vel":3.19,"mpoz":-0.058}}
{"r":{"prb":{"e":1,"x":4.500,"y":19.500,"z":-0.058,"a":0.000,"b":0.000,"c":0.000}},"f":[1,0,0,9833]}
{"sr":{"vel":0.00,"stat":3,"coor":1,"momo":4}}
{"qr":32}
 G0 Z1.0
 G0 X4.5 Y14.5
 G0 Z0.3
G0 Z1.0
{"Lbs":22}
{"r":{},"f":[1,0,8,4401]}
{"sr":{"posz":-0.057,"vel":17.96,"stat":5,"momo":0,"mpoz":-0.057}}
{"qr":31}
G0 X4.5 Y14.5
{"Lbs":8}
{"r":{},"f":[1,0,14,73]}
{"sr":{"posz":-0.038,"vel":170.28,"mpoz":-0.038}}
{"qr":30}
G0 Z0.3
{"Lbs":0}
{"r":{},"f":[1,0,8,4401]}
{"sr":{"posz":0.075,"vel":646.26,"mpoz":0.075}}
{"qr":29}
{"qr":30}
{"sr":{"posy":16.724,"posz":1.000,"vel":1200.00,"mpoy":16.724,"mpoz":1.000}}
{"qr":31}
{"sr":{"posy":14.500,"posz":0.300,"vel":0.00,"stat":3,"mpoy":14.500,"mpoz":0.300}}
{"qr":32}
 G38.2 Z-1.5 F32
{"Lbs":0}
{"r":{},"f":[1,0,16,75]}
{"sr":{"stat":7,"coor":0}}
{"qr":32}
{"qr":31}
{"sr":{"posz":0.170,"vel":32.00,"momo":1,"mpoz":0.170}}
{"sr":{"posz":0.040,"mpoz":0.037}}
{"sr":{"posz":-0.045,"vel":3.19,"mpoz":-0.045}}
{"r":{"prb":{"e":1,"x":4.500,"y":14.500,"z":-0.045,"a":0.000,"b":0.000,"c":0.000}},"f":[1,0,0,3136]}
{"sr":{"vel":0.00,"stat":3,"coor":1,"momo":4}}
{"qr":32}
```

.. could be that G38? I get one set of those errors in the console on every 'step' of the check

**Comment by dgtlmoon** [comment]
I might close this issue for now, seems to be working reliably but with that above errors which I'm not sure is todo with this issue directly, thanks a bunch!
